import {defineStore} from 'pinia';
import {locationsLib} from "../database/locationsLib.js";
import {npcDialogs} from "../database/dialogsLib.js";
import npcsLib from "../database/npcsLib.js";
import {markRaw} from "vue";
import {resourcesLib} from "../database/resourcesLib.js";
import {Notify} from "quasar";

export const useGameStore = defineStore('game', {
    state: () => ({
        game: undefined,
        currentSceneName: undefined,
        scene: undefined,
        hoveredCreatureId: undefined,
        tooltip: {
            show: false,
            text: '',
            position: {x: 0, y: 0}
        },
        inventory: [
            {
                id: 'gold',
                amount: 1000,
            },
            {
                id: 'craft_shard_fire_common',
                amount: 9,
            },
            {
                id: 'craft_shard_water_common',
                amount: 9,
            },
            {
                id: 'craft_shard_grass_common',
                amount: 9,
            },
            {
                id: 'craft_shard_beast_common',
                amount: 9,
            },
            {
                id: 'craft_shard_bird_common',
                amount: 9,
            },
            {
                id: 'craft_shard_reptile_common',
                amount: 9,
            },
            {
                id: 'craft_shard_rage_common',
                amount: 9,
            },
            {
                id: 'craft_shard_hope_common',
                amount: 9,
            },
            {
                id: 'craft_shard_passion_common',
                amount: 9,
            },
        ],
        knownCreatures: [
            '001',
        ],
        creatures: [
            {
                "name": "Пирохват",
                "number": "001",
                "element": "fire",
                "shape": "beast",
                "emotion": "rage",
                "baseMaxHealthStat": 148,
                "baseAttackStat": 71,
                "baseDefenseStat": 70,
                "baseWillStat": 48,
                "baseInitiativeStat": 45,
                "baseSpeedStat": 6,
                "baseMaxPP": 14,
                "basePpRegen": 2,
                "id": "c786e8ce-91be-4226-969e-35a7defefa6c",
                "level": 2,
                "maxHealthStat": 148,
                "speedStat": 6,
                "attackStat": 71,
                "defenseStat": 70,
                "initiativeStat": 45,
                "willStat": 48,
                "maxPP": 14,
                "ppRegen": 2,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Светлохвост",
                "number": "010",
                "element": "fire",
                "shape": "beast",
                "emotion": "hope",
                "baseMaxHealthStat": 119,
                "baseAttackStat": 76,
                "baseDefenseStat": 55,
                "baseWillStat": 69,
                "baseInitiativeStat": 81,
                "baseSpeedStat": 7,
                "baseMaxPP": 15,
                "basePpRegen": 5,
                "id": "e02d0c32-5119-4c82-a948-c24ae64db1af",
                "level": 2,
                "maxHealthStat": 119,
                "speedStat": 7,
                "attackStat": 76,
                "defenseStat": 55,
                "initiativeStat": 81,
                "willStat": 69,
                "maxPP": 15,
                "ppRegen": 5,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Взрывной Ёж",
                "number": "019",
                "element": "fire",
                "shape": "beast",
                "emotion": "passion",
                "baseMaxHealthStat": 101,
                "baseAttackStat": 95,
                "baseDefenseStat": 47,
                "baseWillStat": 83,
                "baseInitiativeStat": 78,
                "baseSpeedStat": 8,
                "baseMaxPP": 15,
                "basePpRegen": 4,
                "id": "acfc3c66-1f7c-481b-b8c2-c4f5e1f2e1d1",
                "level": 2,
                "maxHealthStat": 101,
                "speedStat": 8,
                "attackStat": 95,
                "defenseStat": 47,
                "initiativeStat": 78,
                "willStat": 83,
                "maxPP": 15,
                "ppRegen": 4,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Горючий Гриф",
                "number": "007",
                "element": "fire",
                "shape": "bird",
                "emotion": "rage",
                "baseMaxHealthStat": 139,
                "baseAttackStat": 65,
                "baseDefenseStat": 73,
                "baseWillStat": 29,
                "baseInitiativeStat": 58,
                "baseSpeedStat": 6,
                "baseMaxPP": 11,
                "basePpRegen": 4,
                "id": "801d3ad4-3c3a-48fc-9746-dab69b8bbf1d",
                "level": 2,
                "maxHealthStat": 139,
                "speedStat": 6,
                "attackStat": 65,
                "defenseStat": 73,
                "initiativeStat": 58,
                "willStat": 29,
                "maxPP": 11,
                "ppRegen": 4,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Искорка-Невидимка",
                "number": "016",
                "element": "fire",
                "shape": "bird",
                "emotion": "hope",
                "baseMaxHealthStat": 118,
                "baseAttackStat": 66,
                "baseDefenseStat": 52,
                "baseWillStat": 103,
                "baseInitiativeStat": 91,
                "baseSpeedStat": 8,
                "baseMaxPP": 16,
                "basePpRegen": 5,
                "id": "e3590d6d-f7b5-4972-ad79-bcdde65bbaeb",
                "level": 2,
                "maxHealthStat": 118,
                "speedStat": 8,
                "attackStat": 66,
                "defenseStat": 52,
                "initiativeStat": 91,
                "willStat": 103,
                "maxPP": 16,
                "ppRegen": 5,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Испепеляющий Воробей",
                "number": "025",
                "element": "fire",
                "shape": "bird",
                "emotion": "passion",
                "baseMaxHealthStat": 103,
                "baseAttackStat": 117,
                "baseDefenseStat": 51,
                "baseWillStat": 79,
                "baseInitiativeStat": 112,
                "baseSpeedStat": 9,
                "baseMaxPP": 15,
                "basePpRegen": 6,
                "id": "93a01310-3907-494e-adc9-bd8e8256703f",
                "level": 2,
                "maxHealthStat": 103,
                "speedStat": 9,
                "attackStat": 117,
                "defenseStat": 51,
                "initiativeStat": 112,
                "willStat": 79,
                "maxPP": 15,
                "ppRegen": 6,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Тлеющий Панцирник",
                "number": "004",
                "element": "fire",
                "shape": "reptile",
                "emotion": "rage",
                "baseMaxHealthStat": 167,
                "baseAttackStat": 72,
                "baseDefenseStat": 105,
                "baseWillStat": 39,
                "baseInitiativeStat": 66,
                "baseSpeedStat": 5,
                "baseMaxPP": 12,
                "basePpRegen": 3,
                "id": "7d23a52d-ab9b-4270-a155-231a6bcf7424",
                "level": 2,
                "maxHealthStat": 167,
                "speedStat": 5,
                "attackStat": 72,
                "defenseStat": 105,
                "initiativeStat": 66,
                "willStat": 39,
                "maxPP": 12,
                "ppRegen": 3,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Кристально-Пламенный Страж",
                "number": "013",
                "element": "fire",
                "shape": "reptile",
                "emotion": "hope",
                "baseMaxHealthStat": 126,
                "baseAttackStat": 52,
                "baseDefenseStat": 68,
                "baseWillStat": 120,
                "baseInitiativeStat": 73,
                "baseSpeedStat": 6,
                "baseMaxPP": 18,
                "basePpRegen": 5,
                "id": "82937105-2fb7-4b56-979a-be7598917901",
                "level": 2,
                "maxHealthStat": 126,
                "speedStat": 6,
                "attackStat": 52,
                "defenseStat": 68,
                "initiativeStat": 73,
                "willStat": 120,
                "maxPP": 18,
                "ppRegen": 5,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Огнекусака",
                "number": "022",
                "element": "fire",
                "shape": "reptile",
                "emotion": "passion",
                "baseMaxHealthStat": 100,
                "baseAttackStat": 109,
                "baseDefenseStat": 50,
                "baseWillStat": 71,
                "baseInitiativeStat": 63,
                "baseSpeedStat": 7,
                "baseMaxPP": 15,
                "basePpRegen": 4,
                "id": "d9b8f056-ecb0-49df-bd2b-8d9b06f23a88",
                "level": 2,
                "maxHealthStat": 100,
                "speedStat": 7,
                "attackStat": 109,
                "defenseStat": 50,
                "initiativeStat": 63,
                "willStat": 71,
                "maxPP": 15,
                "ppRegen": 4,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Огненный коготь",
                    "element": "fire",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.9,
                    "critChance": 0.05,
                    "effects": [{"effect": "burn", "chance": 0.4, "duration": 3}],
                    "pp": 7,
                    "cooldown": 1,
                    "id": 100
                }]
            }, {
                "name": "Ледорыт",
                "number": "055",
                "element": "water",
                "shape": "beast",
                "emotion": "rage",
                "baseMaxHealthStat": 149,
                "baseAttackStat": 64,
                "baseDefenseStat": 90,
                "baseWillStat": 40,
                "baseInitiativeStat": 58,
                "baseSpeedStat": 6,
                "baseMaxPP": 12,
                "basePpRegen": 5,
                "id": "cbaa32a8-d415-45e1-aa0f-7f5954649a1c",
                "level": 2,
                "maxHealthStat": 149,
                "speedStat": 6,
                "attackStat": 64,
                "defenseStat": 90,
                "initiativeStat": 58,
                "willStat": 40,
                "maxPP": 12,
                "ppRegen": 5,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Пузырьковая Фея",
                "number": "064",
                "element": "water",
                "shape": "beast",
                "emotion": "hope",
                "baseMaxHealthStat": 135,
                "baseAttackStat": 62,
                "baseDefenseStat": 67,
                "baseWillStat": 67,
                "baseInitiativeStat": 81,
                "baseSpeedStat": 7,
                "baseMaxPP": 17,
                "basePpRegen": 4,
                "id": "c35ff3fb-d99a-47ae-b05f-4c60ef3c02b6",
                "level": 2,
                "maxHealthStat": 135,
                "speedStat": 7,
                "attackStat": 62,
                "defenseStat": 67,
                "initiativeStat": 81,
                "willStat": 67,
                "maxPP": 17,
                "ppRegen": 4,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Водоворотный Рысак",
                "number": "073",
                "element": "water",
                "shape": "beast",
                "emotion": "passion",
                "baseMaxHealthStat": 112,
                "baseAttackStat": 106,
                "baseDefenseStat": 56,
                "baseWillStat": 78,
                "baseInitiativeStat": 77,
                "baseSpeedStat": 8,
                "baseMaxPP": 15,
                "basePpRegen": 6,
                "id": "6470ff19-1642-474c-9e1b-d6e347f691ea",
                "level": 2,
                "maxHealthStat": 112,
                "speedStat": 8,
                "attackStat": 106,
                "defenseStat": 56,
                "initiativeStat": 77,
                "willStat": 78,
                "maxPP": 15,
                "ppRegen": 6,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Штормовой Бастион",
                "number": "061",
                "element": "water",
                "shape": "bird",
                "emotion": "rage",
                "baseMaxHealthStat": 133,
                "baseAttackStat": 63,
                "baseDefenseStat": 89,
                "baseWillStat": 36,
                "baseInitiativeStat": 58,
                "baseSpeedStat": 7,
                "baseMaxPP": 12,
                "basePpRegen": 3,
                "id": "2b1072bb-306d-452d-a663-bae1cbcd254e",
                "level": 2,
                "maxHealthStat": 133,
                "speedStat": 7,
                "attackStat": 63,
                "defenseStat": 89,
                "initiativeStat": 58,
                "willStat": 36,
                "maxPP": 12,
                "ppRegen": 3,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Росинка-Хранитель",
                "number": "070",
                "element": "water",
                "shape": "bird",
                "emotion": "hope",
                "baseMaxHealthStat": 122,
                "baseAttackStat": 56,
                "baseDefenseStat": 61,
                "baseWillStat": 126,
                "baseInitiativeStat": 105,
                "baseSpeedStat": 9,
                "baseMaxPP": 20,
                "basePpRegen": 5,
                "id": "ceaab039-8fb3-4202-9c2a-ddcaae694c33",
                "level": 2,
                "maxHealthStat": 122,
                "speedStat": 9,
                "attackStat": 56,
                "defenseStat": 61,
                "initiativeStat": 105,
                "willStat": 126,
                "maxPP": 20,
                "ppRegen": 5,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Пульсарный Прыгун",
                "number": "079",
                "element": "water",
                "shape": "bird",
                "emotion": "passion",
                "baseMaxHealthStat": 94,
                "baseAttackStat": 97,
                "baseDefenseStat": 50,
                "baseWillStat": 101,
                "baseInitiativeStat": 105,
                "baseSpeedStat": 10,
                "baseMaxPP": 17,
                "basePpRegen": 7,
                "id": "77c104fd-e0e7-4e6c-87cb-9997a60f6c28",
                "level": 2,
                "maxHealthStat": 94,
                "speedStat": 10,
                "attackStat": 97,
                "defenseStat": 50,
                "initiativeStat": 105,
                "willStat": 101,
                "maxPP": 17,
                "ppRegen": 7,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Лазурный Утёс",
                "number": "058",
                "element": "water",
                "shape": "reptile",
                "emotion": "rage",
                "baseMaxHealthStat": 170,
                "baseAttackStat": 62,
                "baseDefenseStat": 109,
                "baseWillStat": 17,
                "baseInitiativeStat": 63,
                "baseSpeedStat": 5,
                "baseMaxPP": 10,
                "basePpRegen": 4,
                "id": "8c43cb7a-0a66-4f80-89d7-3e93ebe758d6",
                "level": 2,
                "maxHealthStat": 170,
                "speedStat": 5,
                "attackStat": 62,
                "defenseStat": 109,
                "initiativeStat": 63,
                "willStat": 17,
                "maxPP": 10,
                "ppRegen": 4,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Живой Каскад",
                "number": "067",
                "element": "water",
                "shape": "reptile",
                "emotion": "hope",
                "baseMaxHealthStat": 136,
                "baseAttackStat": 50,
                "baseDefenseStat": 76,
                "baseWillStat": 107,
                "baseInitiativeStat": 55,
                "baseSpeedStat": 6,
                "baseMaxPP": 18,
                "basePpRegen": 4,
                "id": "bfdf77d3-e46c-4c67-af4f-b7b00343ab7c",
                "level": 2,
                "maxHealthStat": 136,
                "speedStat": 6,
                "attackStat": 50,
                "defenseStat": 76,
                "initiativeStat": 55,
                "willStat": 107,
                "maxPP": 18,
                "ppRegen": 4,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Пенноштурм",
                "number": "076",
                "element": "water",
                "shape": "reptile",
                "emotion": "passion",
                "baseMaxHealthStat": 104,
                "baseAttackStat": 97,
                "baseDefenseStat": 47,
                "baseWillStat": 100,
                "baseInitiativeStat": 77,
                "baseSpeedStat": 7,
                "baseMaxPP": 18,
                "basePpRegen": 5,
                "id": "c00807bc-fe24-46ab-986b-f21c65a417a0",
                "level": 2,
                "maxHealthStat": 104,
                "speedStat": 7,
                "attackStat": 97,
                "defenseStat": 47,
                "initiativeStat": 77,
                "willStat": 100,
                "maxPP": 18,
                "ppRegen": 5,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ледяная игла",
                    "element": "water",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 35,
                    "hitChance": 0.8,
                    "critChance": 0.1,
                    "effects": [{"effect": "freeze", "chance": 0.2, "duration": 1}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 102
                }]
            }, {
                "name": "Цветочный Голиаф",
                "number": "028",
                "element": "grass",
                "shape": "beast",
                "emotion": "rage",
                "baseMaxHealthStat": 165,
                "baseAttackStat": 70,
                "baseDefenseStat": 110,
                "baseWillStat": 47,
                "baseInitiativeStat": 73,
                "baseSpeedStat": 6,
                "baseMaxPP": 12,
                "basePpRegen": 3,
                "Комментарий": "Баланс защиты и скорости",
                "winrate": "54,9",
                "%выживаемость": 53,
                "winrate__1": "49,5",
                "%выживаемость__1": 53,
                "id": "93c6e092-6fa8-4a32-a4d4-1a5e1faf97ba",
                "level": 2,
                "maxHealthStat": 165,
                "speedStat": 6,
                "attackStat": 70,
                "defenseStat": 110,
                "initiativeStat": 73,
                "willStat": 47,
                "maxPP": 12,
                "ppRegen": 3,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Пробуждающий Ветер",
                "number": "037",
                "element": "grass",
                "shape": "beast",
                "emotion": "hope",
                "baseMaxHealthStat": 126,
                "baseAttackStat": 59,
                "baseDefenseStat": 72,
                "baseWillStat": 64,
                "baseInitiativeStat": 72,
                "baseSpeedStat": 7,
                "baseMaxPP": 14,
                "basePpRegen": 4,
                "id": "8229d0f0-7cff-4a52-9bc1-bde19387384c",
                "level": 2,
                "maxHealthStat": 126,
                "speedStat": 7,
                "attackStat": 59,
                "defenseStat": 72,
                "initiativeStat": 72,
                "willStat": 64,
                "maxPP": 14,
                "ppRegen": 4,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Корнедолб",
                "number": "046",
                "element": "grass",
                "shape": "beast",
                "emotion": "passion",
                "baseMaxHealthStat": 110,
                "baseAttackStat": 109,
                "baseDefenseStat": 51,
                "baseWillStat": 62,
                "baseInitiativeStat": 99,
                "baseSpeedStat": 8,
                "baseMaxPP": 16,
                "basePpRegen": 4,
                "id": "8bb0e47c-be70-49f6-830b-69e3d9a4b130",
                "level": 2,
                "maxHealthStat": 110,
                "speedStat": 8,
                "attackStat": 109,
                "defenseStat": 51,
                "initiativeStat": 99,
                "willStat": 62,
                "maxPP": 16,
                "ppRegen": 4,
                "actions": [{
                    "name": "Толчок",
                    "element": "",
                    "shape": "beast",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 28,
                    "hitChance": 0.85,
                    "critChance": 0.06,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 103
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Скальный Филин",
                "number": "034",
                "element": "grass",
                "shape": "bird",
                "emotion": "rage",
                "baseMaxHealthStat": 149,
                "baseAttackStat": 65,
                "baseDefenseStat": 91,
                "baseWillStat": 38,
                "baseInitiativeStat": 79,
                "baseSpeedStat": 8,
                "baseMaxPP": 12,
                "basePpRegen": 3,
                "id": "7c29e43b-52b1-4718-8fc5-eaddbde2c937",
                "level": 2,
                "maxHealthStat": 149,
                "speedStat": 8,
                "attackStat": 65,
                "defenseStat": 91,
                "initiativeStat": 79,
                "willStat": 38,
                "maxPP": 12,
                "ppRegen": 3,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Пушинка Рассвета",
                "number": "043",
                "element": "grass",
                "shape": "bird",
                "emotion": "hope",
                "baseMaxHealthStat": 135,
                "baseAttackStat": 57,
                "baseDefenseStat": 68,
                "baseWillStat": 130,
                "baseInitiativeStat": 94,
                "baseSpeedStat": 10,
                "baseMaxPP": 20,
                "basePpRegen": 4,
                "id": "24d93569-bf95-4283-bfdc-40d83f6161ae",
                "level": 2,
                "maxHealthStat": 135,
                "speedStat": 10,
                "attackStat": 57,
                "defenseStat": 68,
                "initiativeStat": 94,
                "willStat": 130,
                "maxPP": 20,
                "ppRegen": 4,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Листодротик",
                "number": "052",
                "element": "grass",
                "shape": "bird",
                "emotion": "passion",
                "baseMaxHealthStat": 88,
                "baseAttackStat": 109,
                "baseDefenseStat": 53,
                "baseWillStat": 73,
                "baseInitiativeStat": 81,
                "baseSpeedStat": 11,
                "baseMaxPP": 17,
                "basePpRegen": 6,
                "id": "4a229345-6495-4d33-b5d3-b22f9c140ef6",
                "level": 2,
                "maxHealthStat": 88,
                "speedStat": 11,
                "attackStat": 109,
                "defenseStat": 53,
                "initiativeStat": 81,
                "willStat": 73,
                "maxPP": 17,
                "ppRegen": 6,
                "actions": [{
                    "name": "Удар",
                    "element": "",
                    "shape": "bird",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Атакующий",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.9,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 104
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Камнекорень",
                "number": "031",
                "element": "grass",
                "shape": "reptile",
                "emotion": "rage",
                "baseMaxHealthStat": 150,
                "baseAttackStat": 75,
                "baseDefenseStat": 115,
                "baseWillStat": 22,
                "baseInitiativeStat": 62,
                "baseSpeedStat": 5,
                "baseMaxPP": 12,
                "basePpRegen": 3,
                "id": "8430f9f5-59d6-44d4-91bf-f8c7513b8dcd",
                "level": 2,
                "maxHealthStat": 150,
                "speedStat": 5,
                "attackStat": 75,
                "defenseStat": 115,
                "initiativeStat": 62,
                "willStat": 22,
                "maxPP": 12,
                "ppRegen": 3,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Лучезарная Змея",
                "number": "040",
                "element": "grass",
                "shape": "reptile",
                "emotion": "hope",
                "baseMaxHealthStat": 134,
                "baseAttackStat": 43,
                "baseDefenseStat": 91,
                "baseWillStat": 97,
                "baseInitiativeStat": 50,
                "baseSpeedStat": 6,
                "baseMaxPP": 21,
                "basePpRegen": 2,
                "id": "25790d01-eb5d-4765-a60b-b67990a2e808",
                "level": 2,
                "maxHealthStat": 134,
                "speedStat": 6,
                "attackStat": 43,
                "defenseStat": 91,
                "initiativeStat": 50,
                "willStat": 97,
                "maxPP": 21,
                "ppRegen": 2,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }, {
                "name": "Семястрел",
                "number": "049",
                "element": "grass",
                "shape": "reptile",
                "emotion": "passion",
                "baseMaxHealthStat": 121,
                "baseAttackStat": 82,
                "baseDefenseStat": 52,
                "baseWillStat": 93,
                "baseInitiativeStat": 73,
                "baseSpeedStat": 7,
                "baseMaxPP": 16,
                "basePpRegen": 4,
                "id": "5a9be00d-9f90-4128-b468-162e6dc4123a",
                "level": 2,
                "maxHealthStat": 121,
                "speedStat": 7,
                "attackStat": 82,
                "defenseStat": 52,
                "initiativeStat": 73,
                "willStat": 93,
                "maxPP": 16,
                "ppRegen": 4,
                "actions": [{
                    "name": "Укус",
                    "element": "",
                    "shape": "reptile",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.12,
                    "effects": [],
                    "pp": 3,
                    "cooldown": 0,
                    "id": 105
                }, {
                    "name": "Ядовитый шип",
                    "element": "grass",
                    "shape": "",
                    "emotion": "",
                    "level": 2,
                    "Тип": "Гибридный",
                    "actionType": "melee",
                    "range": 1,
                    "baseDamage": 30,
                    "hitChance": 0.95,
                    "critChance": 0.1,
                    "effects": [{"effect": "poison", "chance": 0.2, "duration": 3}],
                    "pp": 6,
                    "cooldown": 1,
                    "id": 101
                }]
            }
        ],

        // Сюжетные флаги
        flags: [],

        currentState: 'location', //battle, craft?
        battleConfig: undefined,

        // Локации
        currentLocationId: 'academy',
        currentDialogNpc: null,
        currentDialogNodeId: null,
        visitedLocations: [],
        metNpcs: [],


        // Прогресс диалогов
        dialogProgress: {
            dragomir: {}
        },
    }),
    getters: {
        inventoryObjects(state) {
            return state.inventory.map((item) => {
                return Object.assign({amount: item.amount}, resourcesLib[item.id])
            })
        },
        inventoryShards(state) {
            return state.inventoryObjects.filter(ii => ii.type === 'shard')
        },
        inventoryResources(state) {
            return state.inventoryObjects.filter(ii => ii.type !== 'shard')
        },
        isLocationAvailable: (state) => (locationId) => {
            const location = locationsLib[locationId];
            if (!location) {
                return false
            }
            return location.conditions.every(cond => state.flags[cond]);
        },
        currentLocation(state) {
            if (!state.currentLocationId || !this.isLocationAvailable(state.currentLocationId)) {
                state.moveToLocation('academy') // дополнительно, если не задана локация, то телепортируем в академию
            }

            return locationsLib[state.currentLocationId]
        },
        currentDialog(state) {
            if (state.currentState !== 'dialog') {
                return null
            }

            const npc = npcsLib[this.currentDialogNpc]
            const dialogNode = npcDialogs[this.currentDialogNpc][this.currentDialogNodeId]

            let phrase = dialogNode.npcText;
            if (Array.isArray(phrase)) {
                phrase = phrase[Math.floor(Math.random() * phrase.length)]
            }

            return {
                name: npc.name,
                phrase: phrase,
                options: dialogNode.options,
                image: npc.image
            }
        }
    },
    actions: {
        load() {
        },
        setGame(game) {
            if (!game) {
                this.game = null
                return
            }
            this.game = markRaw(game)
        },
        changeScene(newScene) {
            this.currentSceneName = newScene
            if (!this.scene) {
                return
            }


            this.scene.start(newScene);
        },
        setScene(scene) {
            if (!scene) {
                this.scene = null
                return
            }
            this.scene = markRaw(scene)
        },
        setHoveredCreature(id) {
            this.hoveredCreatureId = id;
        },
        showTooltip(text, position = {x: 0, y: 0}) {
            this.tooltip = {show: true, text, position};
        },
        hideTooltip() {
            this.tooltip.show = false;
        },

        addCreature(creatureData) {
            this.creatures.push(creatureData)
            if (!this.knownCreatures.includes(creatureData.number)) {
                this.knownCreatures.push(creatureData.number);
            }
        },
        inventoryRemove(item, amount = 1) {
            const index = this.inventory.findIndex(ii => ii.id === item.id)
            if (index === -1) {
                return
            }

            this.inventory[index].amount -= amount
            if (this.inventory[index].amount <= 0) {
                this.inventory.splice(index, 1)
            }
        },
        setFlag(flag, value) {
            this.flags[flag] = value;
        },
        addInventoryItem({id, amount}) {
            const index = this.inventory.findIndex(ii => ii.id === id)
            if (index === -1) {
                this.inventory.push({id, amount});
            } else {
                this.inventory[index].amount += amount
                
            }

            const resourceItem = resourcesLib[id]
            if (!resourceItem) {
                return
            }
            Notify.create({
                html: true, // ВАЖНО: разрешаем HTML в иконке
                message: `<img src="${resourceItem.img}" style="width: 24px; height: 24px; border-radius: 50%; object-fit: cover;"> +${amount} ${resourceItem.name}`,
                position: 'top-right',
                timeout: 3000, // исчезнет через 3 секунды
                closeBtn: true,
                color: 'white',
                textColor: 'dark',
            });
        },
        addCreatureExperience(id, exp) {
            // Находим объект по id
            const entity = this.creatures.find(item => item.id === id);

            if (!entity) {
                console.warn(`Entity with id ${id} not found.`);
                return
            }

            // Если объект найден, добавляем опыт
            if (typeof entity.experience === 'number') {
                entity.experience += exp;
            } else {
                entity.experience = exp; // Если experience нет — создаём
            }
        },
        moveToLocation(locationId) {
            if (this.isLocationAvailable(locationId)) {
                this.currentLocationId = locationId;
                if (!this.visitedLocations.includes(locationId)) {
                    this.visitedLocations.push(locationId);
                }
            }
        },
        recordDialogProgress(npcId, nodeId) {
            // Сохраняем прогресс диалога
        },
        startDialog(npcId) {
            const npc = npcsLib[npcId]
            const dialogNodeId = this.getDefaultDialogNodeId(npc)
            if (!npcDialogs[npcId] || !npcDialogs[npcId][dialogNodeId]) {
                return false
            }


            if (!this.metNpcs.includes(npcId)) {
                this.metNpcs.push(npcId);
            }

            this.currentDialogNpc = npcId
            this.currentDialogNodeId = dialogNodeId
            this.currentState = 'dialog'
        },
        getDefaultDialogNodeId(npc) {
            if (!npc.defaultDialog) {
                return 'greeting'
            }

            for (const defaultDialog of npc.defaultDialog) {
                if (defaultDialog.conditions.every(condition => condition(this))) {
                    return defaultDialog.dialogNodeId
                }
            }
            return 'greeting'
        },
        selectDialogOption(dialogNodeId) {
            if (!npcDialogs[this.currentDialogNpc][dialogNodeId]) {
                return false
            }

            this.currentDialogNodeId = dialogNodeId
        },
        endDialog() {
            this.currentDialogNpc = null
            this.currentDialogNodeId = null
            this.currentState = 'location'
        },
        setState(newState) {
            this.currentState = newState;
        },
    },
});
